/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpos.mvc.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import newpos.mvc.controller.CustomerController;
import newpos.mvc.controller.ItemController;
import newpos.mvc.controller.OrderController;
import newpos.mvc.model.Customer;
import newpos.mvc.model.Item;
import newpos.mvc.model.OrderDetails;
import newpos.mvc.model.Orders;

/**
 *
 * @author ASUS
 */
public class OrderView extends javax.swing.JFrame {

    private CustomerController customerController;
    private ItemController itemController;
    private OrderController orderController;
    private List<Orders> orders = new ArrayList<>();
    private Item tempItem;
    private Customer tempCustomer;
    private Double subTotal = 0.0;

    /**
     * Creates new form OrderView
     */
    public OrderView() {
        customerController = new CustomerController();
        itemController = new ItemController();
        orderController = new OrderController();
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblcustID = new javax.swing.JLabel();
        lblitemCode = new javax.swing.JLabel();
        txtCustID = new javax.swing.JTextField();
        txtItemCode = new javax.swing.JTextField();
        btnSearchCustomer = new javax.swing.JButton();
        lblCustName = new javax.swing.JLabel();
        btnSearchItem = new javax.swing.JButton();
        lblItemDescription = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        btnAddToBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnChechOut = new javax.swing.JButton();
        lblSubTotal = new javax.swing.JLabel();
        lblAvailableQuantity = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblShowAvailableQuantity = new javax.swing.JLabel();
        lblShowUnitPrice = new javax.swing.JLabel();
        lblShowSubTotal = new javax.swing.JLabel();
        lblorderID = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orders");
        setLocation(250,100);

        lblTitle.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ORDERS");

        lblcustID.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        lblcustID.setText("Customer ID  :-");

        lblitemCode.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        lblitemCode.setText("Item Code      :-");

        txtCustID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtItemCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnSearchCustomer.setFont(new java.awt.Font("SriLankan", 1, 12)); // NOI18N
        btnSearchCustomer.setText("SEARCH");
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });

        lblCustName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnSearchItem.setFont(new java.awt.Font("SriLankan", 1, 12)); // NOI18N
        btnSearchItem.setText("SEARCH");
        btnSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchItemActionPerformed(evt);
            }
        });

        lblItemDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblQuantity.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        lblQuantity.setText("Quantity        :- ");

        btnAddToBill.setFont(new java.awt.Font("SriLankan", 1, 12)); // NOI18N
        btnAddToBill.setText("ADD TO BILL");
        btnAddToBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToBillActionPerformed(evt);
            }
        });

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOrder);

        btnChechOut.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnChechOut.setText("CHECH OUT");
        btnChechOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChechOutActionPerformed(evt);
            }
        });

        lblSubTotal.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblSubTotal.setText("SUB TOTAL :-");

        lblAvailableQuantity.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        lblAvailableQuantity.setText("Available    :- ");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblShowAvailableQuantity.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N

        lblShowUnitPrice.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N

        lblShowSubTotal.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N

        lblorderID.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        lblorderID.setText("Order ID       :-");

        txtOrderID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnChechOut, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSubTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblShowSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblorderID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcustID)
                                    .addComponent(lblitemCode)
                                    .addComponent(lblQuantity))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtQuantity)
                                    .addComponent(txtCustID)
                                    .addComponent(txtItemCode, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearchItem)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSearchCustomer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblShowUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAddToBill)
                                        .addGap(57, 57, 57)
                                        .addComponent(lblAvailableQuantity)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblShowAvailableQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblorderID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcustID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearchCustomer)
                        .addComponent(lblCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblitemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchItem)
                        .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblShowUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddToBill)
                        .addComponent(lblAvailableQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShowAvailableQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChechOut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(lblShowSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        searchCustomer();
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnSearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchItemActionPerformed
        searchItem();
    }//GEN-LAST:event_btnSearchItemActionPerformed

    private void btnAddToBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToBillActionPerformed
        addToTable();
    }//GEN-LAST:event_btnAddToBillActionPerformed

    private void btnChechOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChechOutActionPerformed
        placeOrder();
    }//GEN-LAST:event_btnChechOutActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OrderView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToBill;
    private javax.swing.JButton btnChechOut;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnSearchItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAvailableQuantity;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblItemDescription;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblShowAvailableQuantity;
    private javax.swing.JLabel lblShowSubTotal;
    private javax.swing.JLabel lblShowUnitPrice;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblcustID;
    private javax.swing.JLabel lblitemCode;
    private javax.swing.JLabel lblorderID;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtCustID;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void searchCustomer() {
        try {
            Customer customer = customerController.searchCustomer(txtCustID.getText());
            if (customer != null) {
                tempCustomer = customer;
                lblCustName.setText(customer.getName());
            } else {
                JOptionPane.showMessageDialog(this, "Customer not Found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void searchItem() {
        try {
            Item item = itemController.searchItem(txtItemCode.getText());
            if (item != null) {
                tempItem = item;
                lblItemDescription.setText(item.getDescription());
                lblShowAvailableQuantity.setText(Integer.toString(item.getQuantity()));
                lblShowUnitPrice.setText("Rs." + item.getUnitPrice());
            } else {
                JOptionPane.showMessageDialog(this, "Item not Found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    private void loadTable() {
        String[] column = {"Item Code", "Description", "Quantity", "Unit Price", "Total"};
        DefaultTableModel dtm = new DefaultTableModel(column, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblOrder.setModel(dtm);
    }

    private void addToTable() {
        Orders order;
        if (tempItem != null) {
            orders.add(order = new Orders(
                    txtOrderID.getText(),
                    tempItem.getItemCoe(),
                    tempItem.getDescription(),
                    tempItem.getUnitPrice(),
                    Integer.parseInt(txtQuantity.getText()),
                    (Integer.parseInt(txtQuantity.getText()) * tempItem.getUnitPrice())
            ));

            DefaultTableModel dtm = (DefaultTableModel) tblOrder.getModel();

            String[] data = {
                order.getItemCode(),
                order.getDescription(),
                Integer.toString(order.getQuantity()),
                Double.toString(order.getUnitPrice()),
                Double.toString(order.getTotalPrice())
            };
            dtm.addRow(data);
            subTotal += order.getTotalPrice();
            lblShowSubTotal.setText("Rs. " + subTotal);
            
            clearForm();
            
        } else {
            JOptionPane.showMessageDialog(this, "Select Item");
        }
    }

    private void placeOrder() {
        OrderDetails orderDetails = new OrderDetails(tempCustomer.getId(), txtOrderID.getText(), new Date(), subTotal);
        try {
            String msg = orderController.placeOrder(orderDetails, orders);
            JOptionPane.showMessageDialog(this, msg);
        } catch (Exception e) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void clearForm() {
        tempItem = null;
        txtItemCode.setText("");
        txtQuantity.setText("");
        lblItemDescription.setText("");
        lblShowAvailableQuantity.setText("");
        lblShowUnitPrice.setText("");
    }
}
